### PR TITLE
Feature/custom producers

### PR DESCRIPTION
**Pull request by doctorwho1**
Add support for aKeyless dynamic secrets:
https://docs.akeyless.io/docs/custom-producer

### CODE REVIEW

**Comment by jaSunny** [comment]
👍 🚀

**Comment by doctorwho1** [comment]
What else do I need in order to merge the PR?

**Comment by liorhasson** [comment]
@renanaAkeyless

**Comment by tuvia-akeyless** [comment]
released in version 1.1.4

**Pull request closed without merging**
