### PR TITLE
Just an example of adding Sensitive tag

### PR DESCRIPTION
**Pull request by idan-gur**
A sample of variable inputs that should be redacted from being outputed as clear text. should be applied to way more resources.

### CODE REVIEW

**Comment by idan-gur** [comment]
@renanaAkeyless 
I'm using the Akeyless Terraform provider as part of my github-ops CI/CD pipeline and I don't want certain values of the resources outputted as a comment in github, and also a lot of other terraform providers use this method of Sensitive variables (For example - https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/iam/access_key.go)

Let me know if this is something that can be done.

Thanks in advance!

**Review by renanaAkeyless — COMMENTED** [review]
Hi, 
thanks for your contribution.
please update the version from v1.0.10 to v1.0.11 (in version file)
and generate the documentation by running:
`go generate`
from the repository root folder

**Comment by idan-gur** [comment]
@renanaAkeyless 
Updated docs and version

**Review by renanaAkeyless — APPROVED** [review]

**Comment by renanaAkeyless** [comment]
duplicate to:
 https://github.com/akeyless-community/terraform-provider-akeyless/pull/18

**Pull request closed without merging**
