### PR TITLE
Docs: add import example for resources where examples already exist

### PR DESCRIPTION
**Pull request by DaniRieker**
With this pull request I'm doing a first initiative to also document the import possibilities on the resources as mentioned in #81 

While digging deeper into the provider docs, I recognized they are generated by [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs). After reading the docs over there, it turns out, that it's even more simple to get the import statement documented. I simply had to create a import.sh file with the correct import-statement within the matching examples folder. After this recreating the docs with the plugin brought the information into the .md-files.

I've added the import.sh file now to all resources where a example directory already existed and also fixed the name of the example directory for akeyless_auth_method_saml to get the example and the import statement into the docs here as well.

As this is my first contribution here, I'm happy to get your feedback on this.

### CODE REVIEW

**Comment by DaniRieker** [comment]
Is there any chance to get this merged? I'm happy to update the branch again but until now I did not get any feedback at all...

**Comment by DaniRieker** [comment]
Still no feedback 😢
I thought of some other changes on the provider as well but if they don't get merged at the end, it's not worth the effort...

**Comment by renanaAkeyless** [comment]
@DaniRieker the docs files are generated we can not change them.. we do have these examples in our public docs:
https://docs.akeyless.io/docs/terraform-provider

**Comment by DaniRieker** [comment]
Hey @renanaAkeyless, 
that's exactly what I did, I've changed the sources which are used by the generator tfplugindocs. Than I rerun this generator and updated the docs with that. If I read the tfplugindocs documentation correct, this is the way it works...

**Comment by renanaAkeyless** [comment]
@DaniRieker thanks i opened a new PR https://github.com/akeyless-community/terraform-provider-akeyless/pull/109

**Comment by DaniRieker** [comment]
Thanks @renanaAkeyless, I've closed the issue referencing your PR 👍

**Comment by DaniRieker** [comment]
Thanks @renanaAkeyless, I've closed the issue referencing your PR 👍

**Pull request closed without merging**
